export const data = [
  {
    id: 1,
    img: "https://images.pexels.com/photos/1972115/pexels-photo-1972115.jpeg?auto=compress&cs=tinysrgb&w=1600",
    img2: "https://images.pexels.com/photos/1163194/pexels-photo-1163194.jpeg?autO=ress&cS=tinysrgb&w=1600",
    title: "Long Sleeve Graphic T-shirt",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium, impedit quis? Libero blanditiis eius dolorem ab modi similique officia nulla?",
    isNew: true,
    oldPrice: 19,
    price: 12,
  },
  {
    id: 2,
    img: "https://images.pexels.com/photos/1759622/pexels-photo-1759622.jpeg?auto=compress&cs=tinysrgb&w=1600",
    title: "Coat",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium, impedit quis? Libero blanditiis eius dolorem ab modi similique officia nulla?",
    isNew: true,
    oldPrice: 19,
    price: 12,
  },
  {
    id: 3,
    img: "https://images.pexels.com/photos/1457983/pexels-photo-1457983.jpeg?auto=compress&cs=tinysrgb&w=1600",
    title: "Skirt",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium, impedit quis? Libero blanditiis eius dolorem ab modi similique officia nulla?",
    oldPrice: 19,
    price: 12,
  },
  {
    id: 4,
    img: "https://images.pexels.com/photos/2065200/pexels-photo-2065200.jpeg?auto=compress&cs=tinysrgb&w=1600",
    title: "Hat",
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium, impedit quis? Libero blanditiis eius dolorem ab modi similique officia nulla?",
    oldPrice: 19,
    price: 12,
  },
];